### ISSUE TITLE
静态文件

### ISSUE THREAD

**Issue by tobyqin** [epis2048/hexo-python-admin#2]
博主你的静态js文件并没有在源代码里。
![image](https://user-images.githubusercontent.com/14037644/75102908-73d45100-562e-11ea-89e2-77cbd198638a.png)
另外 - 项目想法挺好，不过规范化还需要加油啊

**Comment by epis2048** [comment]
谢谢关注~
这个是我高一时候闲的没事写着玩的，现在看起来确实很蛋疼，以后有时间重写一版吧
静态文件的话将_config.yaml中的域名替换为files.epis2048.net就好了，如果您感兴趣我可以给您打包一份
